### ISSUE TITLE
"IPC connect call failed" when running gpg at Docker Hub

### ISSUE THREAD

**Issue by stanvit** [novilabs/docker-vault#2]
Found your `Dockerfile` with the problem description when was trying to solve similar issue myself. Apparently, there's some timing problem when `gpg-agent` can't start before `gpg`'s attempts to use it, so my solution is to start it explicitly:

    RUN apk -U add gnupg && gpg-agent --daemon && gpg ...

**Comment by a86c6f7964** [comment]
thanks, I am trying it.
